### ISSUE TITLE
When multiple queued jobs will at some points stop being distributed to workers

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#533] opened 2021-09-14 09:01 UTC
When there are many analyses running one after the other, the queue eventually gets stuck:

Although in the background it appears to be "running", nothing visibly changes for hours (or days).

When we look at the backend system, it seems like the analysis are in the celery queue but they never get assigned to a worker. 

Note: the current workaround for it is to cancel one of the "running" runs and that unblocks the queue. It's not great, as if this happens in the evening, I can lose easily half a day's worth of run times. It's currently almost impossible to get anything run (unless it's small).

**Comment by sambles** [comment] 2021-12-07 09:54
It appears that this issue is caused by older workers sharing the same celery queue with other models and locking it up with task prefetch.

This is linked to an issue fixed in 1.13.0 [PR 436](https://github.com/OasisLMF/OasisPlatform/pull/436) which overrides the default prefetch value from 4 to 1.  Updating all models on the same queue to above version `1.13.0` should solve the issue.

**Closed by sambles** 2021-12-07 09:54 UTC
